services:
  app:
    build: .
    ports:
      - 5000:5000
    deploy:
      mode: global
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234321
      POSTGRES_DB: main
    command: python3 -m flask run -h 0.0.0.0 -p 5000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    deploy:
      mode: global
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234321
      POSTGRES_DB: main
    ports:
      - 5432:5432
    healthcheck:
        test: ["CMD", "pg_isready", "-d", "main", "-p", "5432", "-U", "user"]
        interval: 4s
        timeout: 4s
        retries: 5
